export const EXPERIENCES = [
  {
    position: 'Software Engineering Bootcamp Fellow',
    short_position: 'SWE Fellow at General Assembly',
    company: 'General Assembly',
    start_date: 'Jun 2024',
    end_date: 'Sept 2024',
    description1: "Completed 500+ hours of expert-led instruction in Javascript, React, Node.js, Python, Django",
    description2: "Hands-on learning of full stack software development in industry's most in-demand technologies",
    description3: "Developed proficiency in software engineering skills through General Assembly's bootcamp program",
    location: 'Seattle, WA',
  },
  {
    position: 'Partner Marketing Program Manager, Marketing Solutions',
    short_position: 'Marketing PM at LinkedIn',
    company: 'LinkedIn',
    start_date: 'Jan 2022',
    end_date: 'Jun 2024',
    description1: "Led the design and execution of a new automated lead routing system that drove over $7M in additional revenue, leveraging data analysis and process optimization.",
    description2: "Spearheaded the implementation of advanced reporting structures using Marketing Mix Modeling (MMM) and Multi-Touch Attribution (MTA) techniques, delivering key insights that shaped strategic decision-making and drove $8M+ in revenue.",
    description3: "",
    location: 'Seattle, WA',
  },
  {
    position: 'Business Operations Program Manager',
    short_position: 'Biz Ops PM at Coupang',
    company: 'Coupang',
    start_date: 'Jul 2021',
    end_date: 'Jan 2022',
    description1: "Led cross-functional teams to develop and improve new item setup processes, achieving a turnaround time under 20 days, utilizing workflow automation, and SLA management to enhance system performance.",
    description2: "Partnered with the tech and operations teams to resolve escalations within stringent SLAs, ensuring alignment between business requirements and technical solutions.",
    description3: "Developed workflows for compliance and item restriction management, enhancing internal systems with process automation to maintain legal and regulatory standards.",
    location: 'Seattle, WA',
  },
  {
    position: 'Marketing & CX Program Manager',
    short_position: 'M&CX PM at Coupang',
    company: 'Coupang',
    start_date: 'Mar 2020',
    end_date: 'Jul 2021',
    description1: "Designed and executed marketing promotion plans using data-driven insights, resulting in a 39% YoY revenue increase and improved conversion rates (+7%).",
    description2: "Collaborated with development teams to enhance onsite merchandising layouts and banners, driving a 16% pageview increase by implementing UI/UX best practices.",
    description3: "",
    location: 'Seattle, WA',
  },
]